### ISSUE TITLE
I can't reproduce the results

### ISSUE THREAD

**Issue by kleinzcy** [LuigiRiz/NOPS#1]
Thanks your work and nice code. When I run experiments according your scripts, I found I can't reproduce your publish results on SemanticPOSS. The results of Fold1 and Fold2 are:
![image](https://user-images.githubusercontent.com/35723500/233226074-ef499e5b-b4fd-4f9f-a368-00cd4c602301.png)

![image](https://user-images.githubusercontent.com/35723500/233226113-4d4421e9-ed80-42e8-8cfd-bcf630e345d3.png)

The results is far away from your publish results. Do I miss something in the scripts? My scripts is 
```
python main_discovery.py -s 1 --dataset SemanticPOSS --offline --adapting_epsilon_sk
```

**Comment by kleinzcy** [comment]
Sorry, it is my error.

**Comment by LuigiRiz** [comment]
I think you are missing some arguments that need to be passed to the script. You should use
* `--num_heads=5` and `--overcluster_factor=3` to have the novel segmentation heads behave as described in our paper;
* `--use_scheduler` to enable the cosine annealing with warmup;
* `--use_uncertainty_queue`, `--use_uncertainty_loss` and `--uncertainty_percentile=0.3` to enable the uncertainty modelling part;

I'll update the readme in the home with these flags to be more clear.
