### ISSUE TITLE
Question about how to test the model with previous trained ckpts.

### ISSUE THREAD

**Issue by Amazingren** [LuigiRiz/NOPS#6]
Ciao @LuigiRiz 

Me again, I am writing to ask how can I test the model again with previous pretrained ckpts?

Best and many thanks,
Bin

**Comment by LuigiRiz** [comment]
Hi,

I've uploaded the code for evaluation. As written also in the updated README.md, you can run it with the command:
```
python main_discover_test.py -s [SPLIT NUMBER] --checkpoint=[PATH TO LIGHTNING CHECKPOINT]
```

If you move checkpoints between different PCs, I suggest you to also pass to the script the flag `--dataset_config=[PATH TO CONFIG]`, to be sure it does not mess up with paths.
Note also that the flags `--set_deterministic` and `--offline` remain available.
Flag `-h` is anyway available for help messages and other available flags.

Hope it helps,

Greetings
Luigi

**Comment by Amazingren** [comment]
Forget this, solved!
```
trainer.validate(
    model = model,
    ckpt_path = ""
)
```

> Hi,
> 
> I've uploaded the code for evaluation. As written also in the updated README.md, you can run it with the command:
> 
> ```
> python main_discover_test.py -s [SPLIT NUMBER] --checkpoint=[PATH TO LIGHTNING CHECKPOINT]
> ```
> 
> If you move checkpoints between different PCs, I suggest you to also pass to the script the flag `--dataset_config=[PATH TO CONFIG]`, to be sure it does not mess up with paths. Note also that the flags `--set_deterministic` and `--offline` remain available. Flag `-h` is anyway available for help messages and other available flags.
> 
> Hope it helps,
> 
> Greetings Luigi

Great! Thanks a lot!
Bests,
Bin
