### ISSUE TITLE
can I delete the previously loaded weights file

### ISSUE THREAD

**Issue by 2814894078** [LuigiRiz/NOPS#8]
If I start a new round of training, for example, I'm now going to run SemanticPOSS-s0. After the code loads the weights, I want to simultaneously run the SemanticPOSS-s1 dataset. To avoid the code loading the previously generated SemanticPOSS-s0/weights.pt file, which might cause errors, can I delete the previously loaded weights file at that time? This would allow me to run the SemanticPOSS-s1 dataset simultaneously. I'm eagerly awaiting your response!

**Comment by LuigiRiz** [comment]
It's not safe to delete this file as it gets updated epoch by epoch with the optimization of the network. What I usually do to run multiple runs on my cluster is to run the scripts in different folders, as the scripts saves `weights.pt` in the current folder, not in the code folder. Doing so, the file is not overwritten.
Hope this help!

**Comment by 2814894078** [comment]
Thank you very much for your answer
